### ISSUE TITLE
Alpine v3 compatability

### ISSUE THREAD

**Issue by allmarkedup** [SimoTod/alpine-turbo-drive-adapter#40] opened 2021-06-19 00:47 UTC
Hey - this adapter is great (thank you!) but I'm just playing around with a project that is using Alpine v3.x and as far as I can tell they do not play nicely together.

Are you planning on creating a v3-compatible version at any point? Do you think it's even possible with changes to the Alpine API (i.e. `Alpine.discoverUninitializedComponents` etc seems to not exist anymore)? 

If you are not planning on updating it I can try to dig in to see if I can figure out what might need to be done to port it over as it's pretty key for a few projects of mine.

Thanks again 👍

**Comment by SimoTod** [comment] 2021-06-19 04:34
Hi, I'll eventually release a v3 compatibile version but i haven't looked into it yet. I think it's possible using either Alpine.start or Alpine.initTree (i think the latter has less side effects).

**Comment by HugoDF** [comment] 2021-06-19 09:50
In the meantime here's a basic support plugin for v3 Caleb shared, not sure it captures all edge cases etc

https://gist.github.com/calebporzio/20cf74af4a015644c7bef5166cffd86c

**Comment by allmarkedup** [comment] 2021-06-24 21:28
Thanks for the replies guys, and thanks @HugoDF for pointing me in the direction of that plugin. I've had a play with it and while everything works more or less, I get a lot of flashing across page loads of elements that are using `x-show` and whose visbility state is stored in localstorage. I need to get a reduced test case together to explore it more but it wasn't something I had an issue with using v2.

If I have a chance I'll have a play and see if I can contribute anything back. Thanks again for your help.

**Comment by AndreiMotinga** [comment] 2021-07-30 05:17
do you guys have any idea how to implement this meanwhile? 

I'd like to start building an app using alpine 3. seems like it is a bit nicer than v2. 
But can't get it to work with turbo. Could somebody please help?

**Comment by alexej-d** [comment] 2021-07-30 08:00
This is what you need:
```javascript
document.addEventListener('turbo:before-render', () => {
  let permanents = document.querySelectorAll('[data-turbo-permanent]')

  let undos = Array.from(permanents).map(el => {
      el._x_ignore = true

      return () => {
          delete el._x_ignore
      }
  })

  document.addEventListener('turbo:render', function handler() {
      while(undos.length) undos.shift()()

      document.removeEventListener('turbo:render', handler)
  })
})
```

I also had to add an event listener to each root element inside a template for cleanup:
```html
<template x-for="(item, i) in items" :key="item.hash">
  <div @turbo:before-cache.document="$el.remove()">...</div>
</template>
```

**Comment by bep** [comment] 2021-09-02 11:32
I have spent some time looking into this, and none of the snippets above works beyond the simplest setup. I have written some more about this here: https://github.com/alpinejs/alpine/pull/1995#issuecomment-911565806

**Comment by khrome83** [comment] 2021-09-10 13:59
I really only need this to work for Turbolinks. I had no issues with the deprecated project.

**Comment by Ahmed-Elrayes** [comment] 2021-09-11 23:34
> In the meantime here's a basic support plugin for v3 Caleb shared, not sure it captures all edge cases etc
> 
> https://gist.github.com/calebporzio/20cf74af4a015644c7bef5166cffd86c

for some reason, this one doesn't work with me at all.

**Comment by bep** [comment] 2021-09-14 16:15
I have created a gist (which I will try to remember to update if I find something more clever) with my current best approach to this:

https://gist.github.com/bep/a9809f0cb119e44e8ddbe37dd1e58b50

Note that the above requires the patch in https://github.com/alpinejs/alpine/pull/1995 to work.

There is one limitation, I guess, in the above, which I don't care too much about: Components marked with `data-turbo-permanent` cannot itself create more components once you have navigated (but that should be a rare requirement).

**Comment by khrome83** [comment] 2021-09-28 10:02
So it seems like https://github.com/alpinejs/alpine/pull/2117 was added to Alpine v3 by Caleb, which should give us the ability to solve this issue. 

See here - https://github.com/livewire/livewire/pull/3151#issuecomment-926020270

**Comment by bep** [comment] 2021-09-29 09:40
@khrome83 There are a couple of unresolved issues for Turbo in Alpine V3:

1. The solution in #2117 doesn't really work with Turbo beyond its simplest setup. The only working solution I have found is to use `Alpine.stopObservingMutations()` (not currently exported) and then `Alpine.start()`.
2. There are some [open memory leak issues](https://github.com/alpinejs/alpine/issues) that, depending on how you use Turbo, will ... not be a great experience for people after a while. Note that fixing those should not be too hard, so we'll eventually get there.

**Comment by khrome83** [comment] 2021-09-29 17:18
understood @bep, it does not sound like he is willing to export `stopObservingMutations()`. And it sounds like the defer mutations is not what is needed then.

**Comment by SimoTod** [comment] 2021-09-29 18:45
I'm planning to have a look at v3 + Turbo next week. It's technically possible to stop the mutation observer already without that PR using a private API but it would be good if it wasn't needed because in v3 the mutation observer does other important things

**Comment by bep** [comment] 2021-10-08 19:56
>understood @bep, it does not sound like he is willing to export stopObservingMutations(). 

That is not how I read it. Having AlpineJS work great with Turbo would be a big win for the project. But I do understand the hesitation of randomly exporting new functions from the internal API, which is why it's good to have it backed by some real data, which is why @SimoTod and others' work on this is so important/appreciated.

**Comment by therealbenzene** [comment] 2021-10-22 01:48
> @bep this is the first draft if you want to try it out: https://gist.github.com/SimoTod/de091e93af1416a1af5ece8efc23e608
> 
> I'm still not sure about a few points so it's likely to change a bit but it should fix the core issues

This works for my use cast

**Comment by mikeychowy** [comment] 2021-11-26 13:03
> @bep this is the first draft if you want to try it out: https://gist.github.com/SimoTod/de091e93af1416a1af5ece8efc23e608
> 
> I'm still not sure about a few points so it's likely to change a bit but it should fix the core issues

Hi @SimoTod any update on this? Or will this gist be the final answer for v3? I've been using this in my local environment since a month ago with no significant problems, but I'm still hesitant on introducing it to even staging environment because it's not even a release yet.

If you're having some delay because of your IRL job, that's understandable btw, since it's release season for a lot of companies, I guess I'm just anxious due to no further comments on this. Thank you for the good work.

**Comment by SimoTod** [comment] 2021-11-26 17:26
@mikeychowy it's safe to use as far as I know. I don't use turbo so I forgot about it. I'll tag a release over the weekend.

**Comment by tabishiqbal** [comment] 2021-12-16 03:31
bump

**Comment by SimoTod** [comment] 2021-12-16 09:02
@tabishiqbal The tagged release is still for Alpine v2 (Alpine.discoverUninitializedComponents is v2)

**Comment by matt-harvey** [comment] 2021-12-18 22:58
@SimoTod Just wondering if you are planning to tag that v3 compatible release any time soon? Or are there remaining v3 compatibility issues on  the current main branch that you're aware of?

**Comment by SimoTod** [comment] 2021-12-23 22:40
There was just a minor regression with `x-cloak` when navigating back but it's now fixed. Tagged, better late than never. 😅

**Closed by SimoTod** 2021-12-23 22:40 UTC

**Comment by matt-harvey** [comment] 2021-12-24 10:25
Ah OK, nice one, thanks @SimoTod 😄
